### ISSUE TITLE
DateTimePicker appears blank on ios

### ISSUE THREAD

**Issue by pchrysa** [Osedea/react-native-osd-datetimepicker#1]
For me, In order for your component to work on react-native 0.28.0-rc.0 I had to remove from the style class iosPickerContainer the style "alignItems" otherwise the Modal appears blank.

**Comment by adrienthiery** [comment]
Thanks for the feedback @pchrysa , I indeed didn't test it on newer versions yet.

I'll have a look at it asap :)

**Comment by promptinprod** [comment]
@pchrysa fix in #2
